### PR TITLE
Add support for S3 bucket location

### LINKED ISSUE #524: Add support for S3 bucket location
#### Use Case
We want to check the region of a S3 bucket

#### Example
```
describe s3_bucket('my-bucket') do
  it { should have_location('us-east-1') }
end
```

#### References
* https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/S3/Client.html#get_bucket_location-instance_method
* https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/S3/Types/GetBucketLocationOutput.html

> Buckets in Region `us-east-1` have a LocationConstraint of `null`.

Maybe handle `null` and return `us-east-1` in that case

### PR DESCRIPTION
**Pull request by soruma**
Fix #524.

Add `have_location` to see where S3 is located.

```ruby
describe s3_bucket('my-bucket') do
  it { should have_location('us-east-1') }
end
```

### CODE REVIEW

**Comment by k1LoW** [comment]
Hi @soruma!  Thank you for your commit!!
Could you [update doc](https://github.com/k1LoW/awspec/blob/master/doc/contributing.md#troubleshooting) or merge master for fixing test fail?

**Comment by k1LoW** [comment]
Oops, I see that the aws-sdk has been updated again.
I'll take care of this one!
Thanks for your nice commit!

**Comment by k1LoW** [comment]
Released as v1.23.0.

**Comment by anjo-swe** [comment]
@soruma @k1LoW tried 1.23 locally and it's having issues with `us-east-1`

Maybe need to change
```
      def find_bucket_location(id)
        bucket_location = s3_client.get_bucket_location(bucket: id)
        bucket_location.location_constraint
```
to
```
      def find_bucket_location(id)
        bucket_location = s3_client.get_bucket_location(bucket: id)
        bucket_location.location_constraint.nil? || resp.location_constraint.empty? ? 'us-east-1' : resp.location_constraint
```

Related to my comment in the issue
> Buckets in Region us-east-1 have a LocationConstraint of null.
> Maybe handle null and return us-east-1 in that case

**Comment by soruma** [comment]
Hi @k1LoW

> Oops, I see that the aws-sdk has been updated again.

I found out why it didn't happen locally.
Thank you.

(Reproduced when the latest aws-sdk is installed.)

> tried 1.23 locally and it's having issues with us-east-1

I've only tested with buckets located in `ap-northeast-1`.
I didn't know such a specification of AWS.
I'll fix it.

**Pull request merged**
