### PR TITLE
Feature/sns resource type

### PR DESCRIPTION
**Pull request by glasswalk3r**
Adding AWS SNS Topic features to the project.

### CODE REVIEW

**Comment by glasswalk3r** [comment]
Why the TravisCI is breaking is beyond me... I followed the procedures to generate the documentation and the same tests are passing when executing locally:

```
/home/myself/.rbenv/versions/2.4.4/bin/ruby -I/home/myself/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/lib:/home/myself/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-support-3.8.0/lib /home/myself/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/generator/doc/\*_spec.rb
....................................................................

Finished in 1.54 seconds (files took 3.19 seconds to load)
68 examples, 0 failures

Running RuboCop...
Inspecting 460 files
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................

460 files inspected, no offenses detected
/home/myself/.rbenv/versions/2.4.4/bin/ruby -I/home/myself/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/lib:/home/myself/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-support-3.8.0/lib /home/myself/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/lib/awspec/helper/\*_spec.rb
..............

Finished in 3.55 seconds (files took 3.42 seconds to load)
14 examples, 0 failures

```

**Comment by glasswalk3r** [comment]
From https://travis-ci.org/k1LoW/awspec/jobs/452500148:

```
        -### its(:vpc_id), its(:db_instance_identifier), its(:db_instance_class), its(:engine), its(:db_instance_status), its(:master_username), its(:db_name), its(:endpoint), its(:allocated_storage), its(:instance_create_time), its(:preferred_backup_window), its(:backup_retention_period), its(:db_security_groups), its(:availability_zone), its(:preferred_maintenance_window), its(:pending_modified_values), its(:latest_restorable_time), its(:multi_az), its(:engine_version), its(:auto_minor_version_upgrade), its(:read_replica_source_db_instance_identifier), its(:read_replica_db_instance_identifiers), its(:read_replica_db_cluster_identifiers), its(:license_model), its(:iops), its(:character_set_name), its(:secondary_availability_zone), its(:publicly_accessible), its(:status_infos), its(:storage_type), its(:tde_credential_arn), its(:db_instance_port), its(:db_cluster_identifier), its(:storage_encrypted), its(:kms_key_id), its(:dbi_resource_id), its(:ca_certificate_identifier), its(:domain_memberships), its(:copy_tags_to_snapshot), its(:monitoring_interval), its(:enhanced_monitoring_resource_arn), its(:monitoring_role_arn), its(:promotion_tier), its(:db_instance_arn), its(:timezone), its(:iam_database_authentication_enabled), its(:performance_insights_enabled), its(:performance_insights_kms_key_id), its(:performance_insights_retention_period), its(:enabled_cloudwatch_logs_exports), its(:processor_features), its(:deletion_protection)
        +### its(:vpc_id), its(:db_instance_identifier), its(:db_instance_class), its(:engine), its(:db_instance_status), its(:master_username), its(:db_name), its(:endpoint), its(:allocated_storage), its(:instance_create_time), its(:preferred_backup_window), its(:backup_retention_period), its(:db_security_groups), its(:availability_zone), its(:preferred_maintenance_window), its(:pending_modified_values), its(:latest_restorable_time), its(:multi_az), its(:engine_version), its(:auto_minor_version_upgrade), its(:read_replica_source_db_instance_identifier), its(:read_replica_db_instance_identifiers), its(:read_replica_db_cluster_identifiers), its(:license_model), its(:iops), its(:character_set_name), its(:secondary_availability_zone), its(:publicly_accessible), its(:status_infos), its(:storage_type), its(:tde_credential_arn), its(:db_instance_port), its(:db_cluster_identifier), its(:storage_encrypted), its(:kms_key_id), its(:dbi_resource_id), its(:ca_certificate_identifier), its(:domain_memberships), its(:copy_tags_to_snapshot), its(:monitoring_interval), its(:enhanced_monitoring_resource_arn), its(:monitoring_role_arn), its(:promotion_tier), its(:db_instance_arn), its(:timezone), its(:iam_database_authentication_enabled), its(:performance_insights_enabled), its(:performance_insights_kms_key_id), its(:performance_insights_retention_period), its(:enabled_cloudwatch_logs_exports), its(:processor_features), its(:deletion_protection), its(:listener_endpoint)

```
Doing a quick search for the missing term (`its(:listener_endpoint)`) in the report:

```
[myself@localhost awspec]$ ls -l
total 48
-rw-rw-r--. 1 myself myself  1430 Out 16 11:57 awspec.gemspec
-rw-rw-r--. 1 myself myself  1999 Out 16 11:57 awspec-logo.png
drwxrwxr-x. 2 myself myself    49 Out 16 11:57 bin
drwxrwxr-x. 3 myself myself    77 Nov  7 18:40 doc
drwxrwxr-x. 2 myself myself    20 Out 16 11:57 exe
-rw-rw-r--. 1 myself myself    91 Out 16 11:57 Gemfile
-rw-rw-r--. 1 myself myself 20765 Nov  6 12:43 Gemfile.lock
drwxrwxr-x. 3 myself myself    37 Out 16 11:57 lib
-rw-rw-r--. 1 myself myself  1083 Out 16 11:57 LICENSE.txt
-rw-rw-r--. 1 myself myself  1311 Out 16 11:57 Rakefile
-rw-rw-r--. 1 myself myself  3719 Nov  6 12:29 README.md
drwxrwxr-x. 7 myself myself   102 Out 16 11:57 spec
[myself@localhost awspec]$ ack listener_endpoint
[myself@localhost awspec]$
```

**Comment by k1LoW** [comment]
@glasswalk3r Thank you !!! . I'll merge it and fix some !

**Comment by k1LoW** [comment]
Released as v1.12.0.

**Pull request merged**
