### PR TITLE
add not be allowed action

### PR DESCRIPTION
**Pull request by mdolian**
Instead of checking for actions that a role is allowed, I needed to check to ensure certain actions were denied for a role.  So I added a not_be_allowed_action matcher.  It's a very simple change, I used the code from the be_allowed_action and just changed the eval_decision to look for explicitDeny or implicitDeny.

I can write a test for this if you give me an action that should be denied in your AWS setup.

Thanks!

### CODE REVIEW

**Comment by mdolian** [comment]
I'm going to redo this following your contributing instructions

**Comment by mdolian** [comment]
Guidance on how to get the docs straightened out would be great.  I can't seem to get that test to pass.

**Comment by k1LoW** [comment]
Hi @mdolian 

How about following code?

```
describe iam_group('my-iam-group') do
 it { should_not be_allowed_action('ec2:TerminateInstances') }
end
```
( And, you can use from now )

Regards.

**Comment by mdolian** [comment]
I added a test for iam_group but it seems to fail, is my-iam-group being denied access to ec2:TerminateInstances?

Also, should we be testing iam_user and iam_role with the not_be_allowed_action as well ?

**Comment by k1LoW** [comment]
Hi @mdolian 

## Why fail

Because, awspec's test use stub. (see https://github.com/k1LoW/awspec/blob/master/lib/awspec/stub/iam_group.rb#L76 )

Regards.

**Comment by mdolian** [comment]
My apologies, I'm new to the policy simulator.  Did I write the stub wrong?  I'll get this right eventually...   =)

**Comment by k1LoW** [comment]
stub lock all response. 
If you want to write NG test ( like `should_not` ), you have to create "new" stub file and  "new" spec file.

**Comment by mdolian** [comment]
Creating a brand new stub file and spec file for iam_group, iam_user and iam_role seems less than ideal to me.  We are testing all of the other actions in a single spec file, so I guess I'm confused as to why this is different.  My apologies in advance, a lot of this is new to me.

**Comment by mdolian** [comment]
Digging in a little deeper, I don't believe I can even create a new spec file as I'd also have to add a new type.  The Rakefile has this code:

```
    Awspec::Helper::Type::TYPES.map do |type|
      RSpec::Core::RakeTask.new(type) do |t|
        t.pattern = 'spec/type/' + type + '_spec.rb'
      end
    end
```

I'm going to read up more on stubs and simulate_principle_policy to see what I can figure out.

Thanks

**Comment by mdolian** [comment]
I'm going to table this for now and work on searching for network interfaces by name

**Pull request closed without merging**
