### PR TITLE
Bugfix/no method error

### PR DESCRIPTION
**Pull request by glasswalk3r**
See https://github.com/k1LoW/awspec/issues/421
Added new methods to Awspec::Type::IamPolicy in order to use delegation and check the existence of the policy as returned by the respective finder.
Created the exception Awspec::NoExistingResource to raise an error if the policy is not available.
Extended the unit tests to include those use cases.

### CODE REVIEW

**Comment by glasswalk3r** [comment]
Looks like some smokers are broken, they couldn't even update their gems.

**Comment by glasswalk3r** [comment]
Now all tests passed, but be sure to check on #421 before merging, this PR should be evaluated to define the best approach to fix the issue.

**Comment by k1LoW** [comment]
@glasswalk3r Thank you for your GREAT COMMIT !!! 👍

**Comment by k1LoW** [comment]
Released as v1.14.0.

**Pull request merged**
