### PR TITLE
Add type wafregional

### PR DESCRIPTION
**Pull request by htnosm**
Almost the same implementation as waf_web_acl.

### CODE REVIEW

**Comment by k1LoW** [comment]
@htnosm 👍 👍 👍 LGTM !!! 👍 👍 👍

**Comment by k1LoW** [comment]
@htnosm

 If you are interested, Would you like to release awspec.gem ?

merge this PR -> bump up version (1.17.0) -> gem release ( I use octorelease )

If you are not, I release it !

**Comment by htnosm** [comment]
@k1LoW 
Thank you. I will try it in a few days.
I may ask for support.

**Comment by htnosm** [comment]
Released as v1.17.0.

**Comment by htnosm** [comment]
@k1LoW 
v1.17.0 Released.
Please let me know if there is anything wrong.

**Comment by k1LoW** [comment]
@htnosm GOOOOOOOOD!!!! 👍 👍 👍

**Pull request merged**
