### PR TITLE
fix KMS key finding by alias

### PR DESCRIPTION
**Pull request by frezbo**
Update aws-sdk constraint

### CODE REVIEW

**Comment by frezbo** [comment]
@k1LoW Can this be merged, and a new release chartered on the 0.88.x tag. Is there anything else I need to do?

**Comment by frezbo** [comment]
The tests seems o be hanged, closing and re-opening to trigger again.

**Comment by inokappa** [comment]
@frezbo 

Thank you for your PR and fix.

In awspec.gemspec, "aws-sdk" is defined as follows. ("aws-sdk" is already fixed in v3.)

* https://github.com/k1LoW/awspec/blob/master/awspec.gemspec#L24
* https://github.com/k1LoW/awspec/commit/e92ca58046af997cb600daaba3222fe4b569a20a#diff-7d7687a96ed86339d682bd02759ac0a2

I think that it is not necessary to modify awspec.gemspec.
Also, it seems that the following modifications have already been merged.

* https://github.com/k1LoW/awspec/pull/426/files#diff-14a77e4c6f7642ac05b0743b06b8ae97

Therefore, I can not merge this pull request.
I'm so sorry. 😢 

Please confirm.

Regards.

Youhei

**Comment by frezbo** [comment]
@inokappa I want this to be released into `0.x` branch, not master. We have other tools that still rely on aws sdk v2. Would that be possible?

**Comment by k1LoW** [comment]
@frezbo @inokappa 

> Is it possible to release merged into 0.x?

Yes. 

- 0.x is not supported.
- But this PR is backported from 1.x
- Other 0.x versions are not affected.

THANK YOU ALL !!

**Comment by frezbo** [comment]
@k1LoW thanks for the merge, will you be releasing a `0.8.33` version?

**Comment by frezbo** [comment]
@inokappa Can a new version be released?

**Comment by k1LoW** [comment]
@frezbo 

0.x is not supported. so I will not proactively release a new version of v0.x.

Please use `:github` like following.

```
gem 'awspec', :github => 'k1LoW/awspec', :branch => 'v0.x'
```

**Comment by frezbo** [comment]
@k1LoW Thanks. I'm in an offline mirror so cannot use github. I will continue using the fork and release it manually.

**Pull request merged**
