### PR TITLE
adds eks cluster resource

### PR DESCRIPTION
**Pull request by amukiza**
* Adds support for EKS cluster resource
* **TODO:** Add matcher for cluster nodes

### CODE REVIEW

**Comment by k1LoW** [comment]
@amukiza 
Thank you !! NICE WORK !

Could you run `bundle exec bin/toolbox docgen > doc/resource_types.md` ? ( see https://github.com/k1LoW/awspec/blob/master/doc/contributing.md )

**Comment by amukiza** [comment]
@k1LoW  I might need some help figuring this out. 
I did generate docs but for some reason `doc` tests are still failing on CI. I setup a vagrant box with `ubuntu` and tried all the supported ruby  versions, doc tests still pass locally but not in CI.

```ruby
  1) Awspec::Generator::Doc::Type generate_doc output should be the same as doc/resource_types.md
     Failure/Error: expect(generated).to eq doc
     
       expected: "# Resource Types\n\n[acm](#acm)\n| [alb](#alb)\n| [alb_listener](#alb_listener)\n| [alb_target_group...uld eq 1.0 }\nend\n```\n\n### its(:max_24_hour_send), its(:max_send_rate), its(:sent_last_24_hours)"
            got: "# Resource Types\n\n[acm](#acm)\n| [alb](#alb)\n| [alb_listener](#alb_listener)\n| [alb_target_group...uld eq 1.0 }\nend\n```\n\n### its(:max_24_hour_send), its(:max_send_rate), its(:sent_last_24_hours)"
     
       (compared using ==)
     
       Diff:
       @@ -990,7 +990,7 @@
```
screen shot 2018-10-28 at 12 15 39 am

**Comment by k1LoW** [comment]
@amukiza Yay!!  Thank you !!!!

**Comment by amukiza** [comment]
Thanks! I had a dynamic value in the sub 🤦‍♂️  ` created_at: Time.now`

**Comment by k1LoW** [comment]
Released as v1.11.0.

**Comment by amukiza** [comment]
Thank you so much! I will add matchers for the eks nodes and probably start working on `emr`.

**Comment by k1LoW** [comment]
Released as v1.12.0.

**Pull request merged**
