### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by knakayama**
:)

### CODE REVIEW

**Comment by k1LoW** [comment]
Thank you for your fix.
Please run `bundle exec bin/toolbox docgen > doc/resource_type.md` to regenerate doc (and pass test)

**Comment by knakayama** [comment]
Sorry, rebase & squashed.

Some tests fail...

**Comment by k1LoW** [comment]
Oops!! Sorry!! (rubocop....)

**Comment by k1LoW** [comment]
Thank you!!

**Comment by knakayama** [comment]
:-)

**Pull request merged**
