### PR TITLE
Added have_tag support for security_group

### PR DESCRIPTION
**Pull request by Constantin07**
This PR is to address #175

### CODE REVIEW

**Comment by Constantin07** [comment]
@k1LoW  If I update resource document as per Contribution I get the following build error;
```
/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -I/usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.2/lib:/usr/local/rvm/gems/ruby-2.3.0/gems/rspec-support-3.5.0/lib /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.2/exe/rspec --pattern spec/generator/doc/\*_spec.rb
F...............................

Failures:

  1) Awspec::Generator::Doc::Type generate_doc output should be the same as doc/resource_types.md
     Failure/Error: expect(generated).to eq doc

       expected: "# Resource Types\n\n[ami](#ami)\n| [autoscaling_group](#autoscaling_group)\n| [cloudtrail](#cloudtra...elastictranscoder_pipeline('my-elastictranscoder-pipeline') do\n  it { should be_active }\nend\n```"
            got: "# Resource Types\n\n[ami](#ami)\n| [autoscaling_group](#autoscaling_group)\n| [cloudtrail](#cloudtra...elastictranscoder_pipeline('my-elastictranscoder-pipeline') do\n  it { should be_active }\nend\n```"

       (compared using ==)

       Diff:
       @@ -1444,6 +1444,13 @@

        ### have_tag

       +```ruby
       +describe security_group('my-security-group-name') do
       +  it { should have_tag('env').value('dev') }
       +end
       +```
       +
       +
        ### its(:inbound), its(:outbound)

        ```ruby
     # ./spec/generator/doc/type_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.56354 seconds (files took 0.94413 seconds to load)
32 examples, 1 failure

Failed examples:

rspec ./spec/generator/doc/type_spec.rb:4 # Awspec::Generator::Doc::Type generate_doc output should be the same as doc/resource_types.md

/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby -I/usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.2/lib:/usr/local/rvm/gems/ruby-2.3.0/gems/rspec-support-3.5.0/lib /usr/local/rvm/gems/ruby-2.3.0/gems/rspec-core-3.5.2/exe/rspec --pattern spec/generator/doc/\*_spec.rb failed
```

I don't understand where to look for further ...

**Comment by k1LoW** [comment]
@Constantin07 
awspec resource document is generated by `awspec bin/toolbox docgen`.

If you want to update resource document, you should update `doc/_resource_types/security_group.md`.

(see https://github.com/k1LoW/awspec/blob/master/doc/contributing.md#append-resource-type-document-ex-vpc-resource-be_available)

Regards.

**Comment by Constantin07** [comment]
Thanks @k1LoW, Could you please review the PR?

**Comment by k1LoW** [comment]
Yeah!! Great work!!! LGTM! Thank you!!

**Comment by k1LoW** [comment]
Released as v0.51.0.

**Pull request merged**
