### PR TITLE
Security group permissions check for VPC endpoint prefix list

### LINKED ISSUE #282: Request for support of VPC endpoint testing in security group egress rule
Currently awspec does not support testing of security group outbound rules to endpoints. This is similar to issue https://github.com/k1LoW/awspec/issues/214 which was fixed to allow testing of routes to VPC endpoints in route tables.

We have a security group egress rule

HTTPS TCP 443 pl-xxxxxxxx

which fails when I try to test it 

```its(:outbound) { should be_opened('443').protocol('tcp').for('pl-xxxxxxxx') }```

and does not show as an entry in awspec generate.

### PR DESCRIPTION
**Pull request by pvacey**
Fixes #282

### CODE REVIEW

**Comment by pvacey** [comment]
It looks like the generator is broken by the [previous commit](https://github.com/k1LoW/awspec/commit/b27ab0134c64a00d19ff30e833485da4ed46ac0f)?

**Comment by pvacey** [comment]
The build appears to be failing due to the change in the [previous commit](https://github.com/k1LoW/awspec/commit/b27ab0134c64a00d19ff30e833485da4ed46ac0f).  I am not sure how to fix this.  Please help.

**Comment by k1LoW** [comment]
Hi @pvacey ! Thank you for your commit !! 👍 👍 
LGTM!

**Comment by k1LoW** [comment]
Released as v0.88.0.

**Comment by k1LoW** [comment]
Released as v1.5.3.

**Pull request merged**
