### PR TITLE
Add has security group elasticache

### PR DESCRIPTION
**Pull request by takaishi**
Add to matcher ElastiCache's SecurityGroup.

### CODE REVIEW

**Comment by k1LoW** [comment]
Hi @takaishi ! Thank you !
Could you run `bundle exec bin/toolbox docgen > doc/resource_types.md` ?

**Comment by takaishi** [comment]
@k1LoW Thanks for comment!
I deleted docgen's newline... I fixed.

**Comment by k1LoW** [comment]
LGTM! 👍  @takaishi 
( generated md is not good.. )

**Comment by k1LoW** [comment]
Released as v0.73.0.

**Comment by takaishi** [comment]
Thanks!!!

**Pull request merged**
