### PR TITLE
Update at Fukuoka.rb

### PR DESCRIPTION
**Pull request by k1LoW**
One on One at https://fukuokarb.doorkeeper.jp/events/35710

### CODE REVIEW

**Comment by udzura** [comment]
### TODOs:

* [ ] Fix rubocop warnings
* [ ] Update README?

**Comment by kirikiriyamama** [comment]
:heart:

**Comment by udzura** [comment]
@k1LoW Thank you!

**Comment by k1LoW** [comment]
### One more TODO:

- [ ] Fix undesirable-var-name ( `@resource` and `@real_resource` ... :bow: )

**Comment by k1LoW** [comment]
:bomb: :bomb: :bomb:

**Comment by k1LoW** [comment]
Released as v0.26.0.

**Pull request merged**
