### PR TITLE
Add ec2 `have_classiclink()`

### PR DESCRIPTION
**Pull request by matsuzj**
I add checking classiclink.
Can you review ?

### have_classiclink

```ruby
describe ec2('my-ec2-classic') do
  it { should have_classiclink('my-vpc') }
end
```

### CODE REVIEW

**Comment by k1LoW** [comment]
Thank you for your contribution!!
Prease fight to rubocop. 👊

**Comment by matsuzj** [comment]
done!
Sorry, I don't check rubocop.

**Comment by k1LoW** [comment]
LGTM! Thank you!!

**Comment by k1LoW** [comment]
Released as v0.39.0.

**Pull request merged**
