### PR TITLE
Add CAA record support in route53_hosted_zone

### PR DESCRIPTION
**Pull request by dragon3**
This pull request adds CAA DNS record support in route53_hosted_zone.

About CAA record, please take a look at the following AWS documentations:
- http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#CAAFormat
- http://docs.aws.amazon.com/acm/latest/userguide/setup-caa.html

### CODE REVIEW

**Comment by dragon3** [comment]
It seems the CI build failed due to `doc/resource_types.md` outdated, but the error is not related this change.
https://travis-ci.org/k1LoW/awspec/jobs/290444395#L982

Should I run `docgen` in this pull request?

**Comment by k1LoW** [comment]
Ohayou gozai masu @dragon3 ! I'll check it !!

**Comment by k1LoW** [comment]
@dragon3 LGTM! Thank you!!!

**Comment by k1LoW** [comment]
Released as v0.88.0.

**Comment by k1LoW** [comment]
Released as v1.5.3.

**Pull request merged**
