### PR TITLE
Add type s3_bucket_acl

### PR DESCRIPTION
**Pull request by kirikiriyamama**
Hi, I'd like to test S3 Bucket ACL by using awspec, so I implemented type `s3_bucket_acl`.

### CODE REVIEW

**Comment by k1LoW** [comment]
Thank you for your contribution!

I have question.
What do you want to test by this resource type?

I think https://github.com/kirikiriyamama/awspec/commit/ca6c1066c8780e810e058edf3e83ee22c440fb32#diff-64050facca0ae09bb01a8eab11795b60R4 test S3 bucket existing.

```
describe s3_bucket_acl('bucket-name') do
  it { should exist }
end
```
is nearly equal to
```
describe s3('bucket-name') do
  it { should exist }
end
```

I want to see `s3_bucket_acl` usage.

Thanks.

**Comment by kirikiriyamama** [comment]
Thank you for your review.

I assume code like this.

```ruby
describe s3('bucket-name') do
  its('owner.display_name') { should eq 'owner-name' }
  its('grants.first.permission') { should eq 'FULL_CONTROLL' }
end
```

I understand this way isn't beautiful, therefore if another way exists I want to use it. Do you have an idea?

**Comment by k1LoW** [comment]
↑ `s/s3/s3_bucket_acl/` ???

**Comment by kirikiriyamama** [comment]
Oops :bow:

**Comment by kirikiriyamama** [comment]
I've just fixed the code.

**Comment by kirikiriyamama** [comment]
This is the right code.

```ruby
describe s3('bucket-name') do
  its('owner.display_name') { should eq 'owner-name' }
  its('grants.first.permission') { should eq 'FULL_CONTROLL' }
end
```

**Comment by k1LoW** [comment]
my idea: add `have_acl()` matcher

```ruby
describe s3('bucket-name') do
  it { should have_acl.owner('owner-name').permission('FULL_CONTROLL') }
end
```

**Comment by k1LoW** [comment]
My idea2: 
Add `have_acl()` matcher

```ruby
describe s3('bucket-name') do
  it { should have_acl(owner: 'owner-name', permission: 'FULL_CONTROLL') }
end
```

**Comment by kirikiriyamama** [comment]
Thank you for your advice. I tried to implement the 2nd idea. How about this?

**Comment by k1LoW** [comment]
nice! :+1:
thank you!

**Comment by k1LoW** [comment]
mmm `s3.have_acl()` ...

**Comment by kirikiriyamama** [comment]
I think your opinion is right, however I couldn't come up with a good interface. There are two reasons. The 1st, a bucket has an ACL necessarily. And the 2nd, an ACL can have several grants. Hmm...

**Comment by k1LoW** [comment]
Now... I think I can not leave this implementation, because Aws::S3::Client has many `get_bucket_*` .
(If `s3_bucket_acl` is OK, `s3_bucket_lifecycle`, `s3_bucket_location`, `s3_bucket_cors`, ...  are OK )

screncaptured_2015-11-30_10 05 12

I try other implementation at #79 .

**Pull request merged**
