### PR TITLE
Keep ALB/NLB Llistener condition spec-file compatibility.

### PR DESCRIPTION
**Pull request by yukimochi**
Now sdk changed and returns alb and elb listener conditiion's values redundantly.
Previous implement of awspec are checked precisely match but it needs fix all spec files about this changes.
So this PR changed method,it check only field and values to prevent them.

### CODE REVIEW

**Comment by k1LoW** [comment]
@yukimochi  Thank you for your commit !!!

> Now sdk changed and returns alb and elb listener conditiion's values redundantly.

Could you show me example or document ? 🙏

**Comment by yukimochi** [comment]
[This](https://aws.amazon.com/about-aws/whats-new/2019/03/application-load-balancers-now-support-advanced-request-routing/) may be the reason to change?

### Previous SDK responce
 - SDK Responce (`conditions` in `Aws::ElasticLoadBalancingV2::Client #describe_rules`)
```
{
    field: "path-pattern", 
    values: [
    "/img/*", 
    ], 
}
```
- Structure
```
resp.rules[0].conditions #=> Array
resp.rules[0].conditions[0].field #=> String
resp.rules[0].conditions[0].values #=> Array
resp.rules[0].conditions[0].values[0] #=> String
```
reference: https://web.archive.org/web/20171030203955/https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ElasticLoadBalancingV2/Client.html#describe_rules-instance_method

### New SDK responce
 - SDK Responce (`conditions` in `Aws::ElasticLoadBalancingV2::Client #describe_rules`)
```
{
    "field": "path-pattern",
    "values": [
        "/img/*"
    ],
    "path_pattern_config": {
        "values": [
            "/img/*"
        ]
    }
}
```
- Structure
```
resp.rules[0].conditions #=> Array
resp.rules[0].conditions[0].field #=> String
resp.rules[0].conditions[0].values #=> Array
resp.rules[0].conditions[0].values[0] #=> String
resp.rules[0].conditions[0].host_header_config.values #=> Array
resp.rules[0].conditions[0].host_header_config.values[0] #=> String
resp.rules[0].conditions[0].path_pattern_config.values #=> Array
resp.rules[0].conditions[0].path_pattern_config.values[0] #=> String
resp.rules[0].conditions[0].http_header_config.http_header_name #=> String
resp.rules[0].conditions[0].http_header_config.values #=> Array
resp.rules[0].conditions[0].http_header_config.values[0] #=> String
resp.rules[0].conditions[0].query_string_config.values #=> Array
resp.rules[0].conditions[0].query_string_config.values[0].key #=> String
resp.rules[0].conditions[0].query_string_config.values[0].value #=> String
resp.rules[0].conditions[0].http_request_method_config.values #=> Array
resp.rules[0].conditions[0].http_request_method_config.values[0] #=> String
resp.rules[0].conditions[0].source_ip_config.values #=> Array
resp.rules[0].conditions[0].source_ip_config.values[0] #=> String
```
reference: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ElasticLoadBalancingV2/Client.html#describe_rules-instance_method

**Comment by k1LoW** [comment]
@yukimochi Sorry for the late reply!!

Thank you for your fix. I understand it.

**Comment by k1LoW** [comment]
Released as v1.17.4.

**Pull request merged**
