### PR TITLE
refactor: faster EC2 instance search

### PR DESCRIPTION
**Pull request by glasswalk3r**
Based on available documentation, this PR introduces some assertions to check if the `id` parameter has the expected format of a instance id.

If does, than an attempt to find the instance is attempted, just like the original code.

If the `id` has not a instance id expected format, than an attempt with a tag name is attempted instead, avoiding an API request that would probably fail anyway.

### CODE REVIEW

**Comment by k1LoW** [comment]
@glasswalk3r Thank you for your commitment!

I like the idea of verifying what can be verified in advance before the API call.

But if this change is introduced, it appears that if there is a change in the format of the resource ID ( for example, prefix change `i-` to `ec-i-` ), the search will not work as it did before the change.

I think the test code should run as stably as possible.

**Comment by glasswalk3r** [comment]
Hi @k1LoW ,

You're right, there is a tradeoff.

Unfortunately, there is no way to get to know the format dynamically, only to check if your account has migrated or not to the latest format.

On the other hand, it could take years from now for AWS to change that again (if it will ever happen) and that would probably be a planned modification, with customer being notified well before the change is applied to avoid breaking compatibility.

The instance ID is already at the [second generation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resource-ids.html), no way to predict if it is going to change again or not.

The only way I see to implement compatibility with the old way of `Ec2::find_ec2` is to keep it as is and use an environment variable to adopt the newer behavior... or vice-versa.

What do you think?

**Comment by k1LoW** [comment]
I think the test code should run as stably as possible.

In other words, we believe that stability is better than expansion for faster performance.

**Comment by glasswalk3r** [comment]
> I think the test code should run as stably as possible.
> 
> In other words, we believe that stability is better than expansion for faster performance.

Understood @k1LoW !
I made some new changes, adding a fallback in the case a given `id` that _does not look like_ an EC2 instance ID but does work like one.

It would not only keep things working as expected, but giving us a proper warning that something changed regarding the instance ID format.

**Comment by k1LoW** [comment]
@glasswalk3r Thank you !!! Great !

**Comment by k1LoW** [comment]
Released as v1.24.4.

**Pull request merged**
