### PR TITLE
Add disable_api_termination into ec2

### PR DESCRIPTION
**Pull request by tjinjin**
Hello.
Here's my attempt at adding 'disabled_termination' into ec2 type.

For example
```
describe ec2('i-ec12345a') do
  it { should be_disabled_termination }
end
```

### CODE REVIEW

**Comment by tjinjin** [comment]
Ooops

**Comment by k1LoW** [comment]
Thank you for your Pull Request!!
I want to merge it!

I have 1 question.

Why do you drop `api_` from matcher name?
(You add matcher `be_disabled_termination` instead  of `be_disabled_api_termination`)

(I like `be_disabled_api_termination`, because I use optoin `--disable_api_termination` on CLI http://docs.aws.amazon.com/cli/latest/reference/ec2/modify-instance-attribute.html)

**Comment by tjinjin** [comment]
Thanks a comment!!

I thought that it's too long. But , it should be accurate . Fixed it!

**Comment by k1LoW** [comment]
Nice commit!!! Thank you!!!

**Comment by k1LoW** [comment]
Released as v0.11.0.

**Comment by tjinjin** [comment]
thx!

**Pull request merged**
