### PR TITLE
Add to check  security_groups

### PR DESCRIPTION
**Pull request by takaishi**
Add to check instance's security group wiht array.

So, when instance 'my-ec2' has following security groups:

- my-security-group-name-1
- my-security-group-name-2

This spec is pass.

```
describe ec2('my-ec2') do
  it { should have_security_groups(['my-security-group-name-1', 'my-security-group-name-2']) }
end
```

But, this spec is fail.

```
describe ec2('my-ec2') do
  it { should have_security_groups(['my-security-group-name-1']) }
end
```

### CODE REVIEW

**Comment by k1LoW** [comment]
Hi @takaishi ! 
Thank you for your commit !
Please run `bundle exec bin/toolbox docgen > doc/resource_types.md` to generate doc.

Regards.

**Comment by takaishi** [comment]
@k1LoW 
Thank you for review! Added generated doc and fix rubocop result.

**Comment by k1LoW** [comment]
@takaishi LGTM! 👍

**Comment by k1LoW** [comment]
Released as v0.71.0.

**Pull request merged**
