### PR TITLE
adds support for emr

### PR DESCRIPTION
**Pull request by amukiza**

### CODE REVIEW

**Comment by k1LoW** [comment]
Hi @amukiza . Thank you for NICE COMMIT!

I wrote troubleshooting when CI failed ( https://github.com/k1LoW/awspec/blob/master/doc/contributing.md#troubleshooting )

Could you update aws-sdk-ruby ?

**Comment by amukiza** [comment]
Thanks @k1LoW now tests fail locally as well. I will regenerate the docs.

**Comment by k1LoW** [comment]
@amukiza 

Thank you !!!!!! LGTM !!!!!  🎊

**Comment by k1LoW** [comment]
Released as v1.12.0.

**Pull request merged**
