### PR TITLE
Build fix: generate doc

### PR DESCRIPTION
**Pull request by FlanBr-yopG**
Fix build errors like https://travis-ci.org/k1LoW/awspec/jobs/332172271

Errors that look like this: 
```
Failed examples:

rspec ./spec/generator/doc/type_spec.rb:4 # Awspec::Generator::Doc::Type generate_doc output should be the same as doc/resource_types.md
```

### CODE REVIEW

**Comment by FlanBr-yopG** [comment]
This branch has survived initial tests within the fork: https://travis-ci.org/FlanBr-yopG/awspec/builds/334216596

**Comment by k1LoW** [comment]
Hi @FlanBr-yopG ! Thank you for your help !

## Why fail build?

1. awspec document is auto generated by `docgen`.
2. CI works by [cron jobs](https://docs.travis-ci.com/user/cron-jobs/).
3. When aws-sdk-ruby updated, methods update too.
4. fail docgen build.

**Comment by k1LoW** [comment]
Released as v1.3.0.

**Comment by k1LoW** [comment]
Released as v1.3.1.

**Comment by k1LoW** [comment]
Released as v1.5.3.

**Pull request merged**
