### PR TITLE
Add RDS DB Cluster & Global Cluster

### PR DESCRIPTION
**Pull request by alpineriveredge**

### CODE REVIEW

**Comment by alpineriveredge** [comment]
@k1LoW 
CI / Test (2.1 and 2.2) are failed.
I think these test environment's old aws-sdk would cause failure.
Should I fix stub to remove properties which aws-sdk doesn't have?

**Comment by k1LoW** [comment]
Hi @alpineriveredge . Thank you for your commit!!

Currently awspec supports Ruby 2.1, although the future is not clear.
If possible, I would like it to be error free on Ruby 2.1 as well.

**Comment by alpineriveredge** [comment]
@k1LoW 
Could you update `aws-sdk-core` version?
Ruby 2.1 and 2.2 environments have `aws-sdk-core 3.119.1`.
Ruby 2.3 environment has `aws-sdk-core 3.131.3`.
I think these version difference would cause Ruby 2.1 and 2.2 test failure.

**Comment by k1LoW** [comment]
@alpineriveredge Thank you!!!

**Pull request merged**
