### PR TITLE
Add have_vpc_attribute.

### PR DESCRIPTION
**Pull request by yukimochi**
AWS VPC has VPC_Attributes (enableDnsSupport, enableDnsHostnames).
I want to add support this.

### CODE REVIEW

**Comment by k1LoW** [comment]
Hi @yukimochi !!! Thank you for NICE COMMIT !!!

Could you run `bundle exec bin/toolbox docgen > doc/resource_types.md` ? ( see https://github.com/k1LoW/awspec/blob/master/doc/contributing.md#troubleshooting )

**Comment by yukimochi** [comment]
Thank you for response. Now run `docgen`.

**Comment by k1LoW** [comment]
THANK YOU!! LGTM!

**Comment by k1LoW** [comment]
Released as v1.12.5.

**Comment by k1LoW** [comment]
Released as v1.14.0.

**Pull request merged**
