### PR TITLE
Add rerouce type ses_send_quota and Update Document.

### PR DESCRIPTION
**Pull request by inokappa**
Hi, Koyama san

Otukaresama desu.
I added SES Resource type 'ses_send_quota'.

```ruby
require 'spec_helper'
describe ses_send_quota('my-ses') do
  its(:max_24_hour_send) { should eq '200'.to_f }
  its(:max_send_rate) { should eq '1'.to_f }
  its(:sent_last_24_hours) { should eq '1'.to_f }
end
```

Please confirm.

Regards.

Yohei

### CODE REVIEW

**Comment by k1LoW** [comment]
Hi @inokappa !

Perhaps, this is not `ses_send_quota` but `account` type ?

I have no idea about good awspec API, now..

**Comment by inokappa** [comment]
Hi @k1LoW 

Thank you for your comment.

>Perhaps, this is not ses_send_quota but account type ?
>I have no idea about good awspec API, now..

I agree with you but have no idea about it... 🙏 
for example, what you say is like following, isn't it?

```ruby
require 'spec_helper'
describe account('ses') do
  its(:max_24_hour_send) { should eq '200'.to_f }
  its(:max_send_rate) { should eq '1'.to_f }
  its(:sent_last_24_hours) { should eq '1'.to_f }
end
```

**Comment by k1LoW** [comment]
> for example, what you say is like following, isn't it?

Yes //

**Comment by k1LoW** [comment]
Merged by #243. Thank you!

**Comment by k1LoW** [comment]
Released as v0.70.0.

**Pull request closed without merging**
