### PR TITLE
add shared_context to specify region by context

### PR DESCRIPTION
**Pull request by takaishi**
When we have resource in multi region, run test with specified region.

```ruby
# use default region(defined secret.yml)
describe ec2('my-instance-1') do
    it { should exist }
end

# use custom region(defined metadata)
describe ec2('my-instance-2'), region: 'us-east-1' do
    it { should exist }
end
```

### CODE REVIEW

**Comment by k1LoW** [comment]
Wow great change!! 👀

**Comment by igorlg** [comment]
Wow!!! Awesome!

**Comment by k1LoW** [comment]
@takaishi LGTM!!! Great!!!

**Comment by k1LoW** [comment]
Released as v0.56.0.

**Comment by jeremymcgee73** [comment]
Would it be possible to get this added to the docs? I had to use this with Route53 to set the region directly.

```
describe route53_hosted_zone('ZONE ID'), region: 'us-gov-west-1' do
  its(:resource_record_set_count) { should eq 7 }
  it { should have_record_set('example.com.').a('123.456.7.890') }
end
```

I was getting the following error:
```
     Aws::Route53::Errors::SignatureDoesNotMatch:
       Credential should be scoped to a valid region, not 'us-gov-east-1'.
```

**Pull request merged**
